// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContactAttachment.proto

package org.thoughtcrime.securesms.contactshare.model;

public final class ContactAttachmentProtos {
  private ContactAttachmentProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ContactDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:signal.ContactData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes contact = 1;</code>
     */
    boolean hasContact();
    /**
     * <code>optional bytes contact = 1;</code>
     */
    com.google.protobuf.ByteString getContact();

    /**
     * <code>optional bytes avatar = 2;</code>
     */
    boolean hasAvatar();
    /**
     * <code>optional bytes avatar = 2;</code>
     */
    com.google.protobuf.ByteString getAvatar();
  }
  /**
   * Protobuf type {@code signal.ContactData}
   */
  public static final class ContactData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:signal.ContactData)
      ContactDataOrBuilder {
    // Use ContactData.newBuilder() to construct.
    private ContactData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ContactData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ContactData defaultInstance;
    public static ContactData getDefaultInstance() {
      return defaultInstance;
    }

    public ContactData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ContactData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              contact_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              avatar_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.internal_static_signal_ContactData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.internal_static_signal_ContactData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData.class, org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData.Builder.class);
    }

    public static com.google.protobuf.Parser<ContactData> PARSER =
        new com.google.protobuf.AbstractParser<ContactData>() {
      public ContactData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ContactData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ContactData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CONTACT_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString contact_;
    /**
     * <code>optional bytes contact = 1;</code>
     */
    public boolean hasContact() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes contact = 1;</code>
     */
    public com.google.protobuf.ByteString getContact() {
      return contact_;
    }

    public static final int AVATAR_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString avatar_;
    /**
     * <code>optional bytes avatar = 2;</code>
     */
    public boolean hasAvatar() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes avatar = 2;</code>
     */
    public com.google.protobuf.ByteString getAvatar() {
      return avatar_;
    }

    private void initFields() {
      contact_ = com.google.protobuf.ByteString.EMPTY;
      avatar_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, contact_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, avatar_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, contact_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, avatar_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code signal.ContactData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:signal.ContactData)
        org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.internal_static_signal_ContactData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.internal_static_signal_ContactData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData.class, org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData.Builder.class);
      }

      // Construct using org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        contact_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        avatar_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.internal_static_signal_ContactData_descriptor;
      }

      public org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData getDefaultInstanceForType() {
        return org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData.getDefaultInstance();
      }

      public org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData build() {
        org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData buildPartial() {
        org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData result = new org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.contact_ = contact_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.avatar_ = avatar_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData) {
          return mergeFrom((org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData other) {
        if (other == org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData.getDefaultInstance()) return this;
        if (other.hasContact()) {
          setContact(other.getContact());
        }
        if (other.hasAvatar()) {
          setAvatar(other.getAvatar());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.thoughtcrime.securesms.contactshare.model.ContactAttachmentProtos.ContactData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString contact_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes contact = 1;</code>
       */
      public boolean hasContact() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes contact = 1;</code>
       */
      public com.google.protobuf.ByteString getContact() {
        return contact_;
      }
      /**
       * <code>optional bytes contact = 1;</code>
       */
      public Builder setContact(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        contact_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes contact = 1;</code>
       */
      public Builder clearContact() {
        bitField0_ = (bitField0_ & ~0x00000001);
        contact_ = getDefaultInstance().getContact();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString avatar_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes avatar = 2;</code>
       */
      public boolean hasAvatar() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes avatar = 2;</code>
       */
      public com.google.protobuf.ByteString getAvatar() {
        return avatar_;
      }
      /**
       * <code>optional bytes avatar = 2;</code>
       */
      public Builder setAvatar(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        avatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes avatar = 2;</code>
       */
      public Builder clearAvatar() {
        bitField0_ = (bitField0_ & ~0x00000002);
        avatar_ = getDefaultInstance().getAvatar();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:signal.ContactData)
    }

    static {
      defaultInstance = new ContactData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:signal.ContactData)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_ContactData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_signal_ContactData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027ContactAttachment.proto\022\006signal\".\n\013Con" +
      "tactData\022\017\n\007contact\030\001 \001(\014\022\016\n\006avatar\030\002 \001(" +
      "\014BH\n-org.thoughtcrime.securesms.contacts" +
      "hare.modelB\027ContactAttachmentProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_signal_ContactData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_signal_ContactData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_signal_ContactData_descriptor,
        new java.lang.String[] { "Contact", "Avatar", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
